### ISSUE TITLE
您是如何下载Android Support Library, revision 23.4.0 (May 2016)的呢？

### ISSUE THREAD

**Issue by gongzelong0718** [wuchangfeng/ZhuanLan#1]
观察到您引用了它，

我的SDK MANAGER没有更新出新的包。
我去官网看到了介绍，没找到去哪里下载它。

期待您的回复。

**Comment by wuchangfeng** [comment]
@gongzelong0718 说真的,我没有刻意去下载。只不过,这个是个人练习作品,然后我用的 AS 是最新的 2.2  Preview 4 开发的。有可能是这个版本自带的。另外,你也可以体验一下最新的版本,速度效率上提高了不少感觉。
希望能够帮助你。

**Comment by gongzelong0718** [comment]
我尝试了一下，在下载android support library上依然会有问题，甚至会卡死。您下载的是哪个2.2preview也有好几个，您下载的是SHA-1是655B20A12E7D5A05A72BEF860653828C06B037A1吗？或者您能不能加我下QQ，传给我一下那个文件夹。我感觉AS在这方面好像有一些BUG

**Comment by gongzelong0718** [comment]
841057341，我的QQ

**Comment by wuchangfeng** [comment]
@gongzelong0718 加了

**Comment by gongzelong0718** [comment]
搞定了，这个Issue可以关闭了。下载最新的Android Support Repository version 33就可以。
android support library和Android Support Repository还是有不同的，以前没有注意到。
