### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by nakisaren** [wuchangfeng/ZhuanLan#2]
你好 我运行你的demo后 报这个错，然后搜了下网上的类似问题，比较多的说是java版本的问题，我这边用的是1.7的，想问下你这边是1.8还是什么版本，或者你有没有遇到类似问题。

**Comment by wuchangfeng** [comment]
不好意思。才看见。是的。我用的是 jdk1.8。
有什么问题可以qq交流。437806668
